
let str = "THERE ARE TOO MANY ISSUES TO QUANTIFY AND RANK\n\nTHIS CAMPUS CAN BE VERY DIFFICULT FOR THOSE WHO HAVE BEEN HISTORICALLY MARGINALIZED\n\nA LOT OF BIAS TOWARDS POC FROM BOTH STUDENTS AND STAFF\n\nTHERE SHOULD BE MORE DONE TO GET STUDENTS TO THINK ABOUT SYSTEMIC RACISM AND HOW IT CAN SUBTLY MANIFEST ITSELF IN EVERYDAY LIVES\n\nMY FIRST MONTH HERE A STUDENT SCREAMED AT ME ABOUT HOW IT WASNT HIS FAULT WHITE PEOPLE KILLED NATIVE AMERICANS OR DID SLAVERY. HE THEN TOLD ME I WAS THE PROBLEM. I TOOK THE INCIDENT TO THE ADMINISTRATION AND THEY DID NOTHING.\n\nINSUFFICIENT COMMUNICATION METHODS\n\nAN UNFRIENDLY AND UNINVITING ADMINISTRATION\n\nSTUDENT RESENTMENT\n\nADMIN TREAT US LIKE BABIES\n\nJUDGEMENT FROM TEACHERS\n\nI STOPPED PURSUING THE ECON MAJOR DUE TO THE FACT THAT I DIDNT WANT TO BE CONSTANTLY PROVING MYSELF IN A BOYS CLUB FOR THE NEXT THREE YEARS\n\nTHERES NOT ONE PROFESSOR OF COLOR IN THE ECON DEPARTMENT\n\nADMINISTRATORS AND CAMPUS AT LARGE TREATING ME AND MY COMMUNITIES AS IF THEY DONT CARE ABOUT US\n\nA PROFESSOR CALLED ME PERSONALLY INTO HER OFFICE TO TELL ME TO STOP TALKING ABOUT BLACK AMERICAN POLITICS\n\nMAKING BLACK PEOPLE FIND THE GOOD IN RACIST SYSTEMS IS VIOLENCE\n\nADMINISTRATION REFUSES TO HELP ME FIGURE OUT A FINANCIALLY RESPONSIBLE WAY TO CONTINUE TO AFFORD TUITION\n\nCONSTRICTIONS ON CLASSES\n\nTHE REGISTRAR COMPLETELY FUCKS YOU OVER\n\nSTUDENTS SHOULD NOT HAVE TO BE LATE TO CLASS BECAUSE THERE ARE NO OPEN PARKING SPACES\n\nLACK OF SOCIAL SPACES\n\nAN OFTEN OBTUSE AND FORBIDDING SOCIAL SCENE\n\nTHE SCHOOL SOCIAL SCENE ON CAMPUS IS PRETTY BORING\n\nHONESTLY LC IS WHERE FUN GOES TO DIE\n\nSTRANGE SOCIAL CULTURE\n\nTERRIBLE SOCIAL INTERACTIONS\n\nA LACK OF CAMPUS COMMUNITY\n\nTHE LACK OF COMMUNITY AT LC IS THE BIGGEST PROBLEM\n\nDESPITE HAVING BEEN HERE MULTIPLE YEARS I HAVE NEVER FELT ITS A PLACE WHERE THERE IS ANY SENSE OF COMMUNITY\n\nLACK OF COMMUNITY\n\nLACK OF SCHOOL SPIRIT\n\nIT IS HARD TO FIND CAMARADERIE AND COMMUNITY ON CAMPUS\n\nAN INGRAINED HEIR OF BEING COOL OR SUBDUED AS THE NORM\n\nA LACK OF STUDENT ENGAGEMENT, IDLENESS, AND TOO COOL CULTURE\n\nEVERYONE IS NOT OPEN TO GETTING TO KNOW NEW PEOPLE\n\nMAKING FRIENDS\n\nCLIQUE-INESS\n\nCLIQUES\n\nOFTEN IT FEELS LIKE EVERYONE IS TOO BUSY POSTURING HOW COOL THEY ARE TO ACTUALLY GET TO KNOW ONE ANOTHER\n\nNOT A GREAT DATING POOL\n\nFINDING LOVE\n\nTHE ADMINISTRATION CONTINUALLY LETS SEXUAL OFFENDERS INHABIT THE SAME SPACES THEIR SURVIVORS DO\n\nRAPE CULTURE ON CAMPUS\n\nTHE SHEER NUMBER OF SEXUAL ASSAULTS THAT HAPPEN ON CAMPUS\n\nWILL YOU ACTUALLY START REMOVING RAPISTS FROM CAMPUS? OR JUST LET THEM DROP OUT SO YOU DON’T HAVE TO DEAL WITH IT?\n\nTHE SCHOOL IS NOT DOING A GOOD ENOUGH JOB QUELLING THE RAPE CULTURE THAT IS PREVALENT IN OUR COMMUNITY\n\nA WHITE CAMPO OFFICER CALLED ME A DOG MULTIPLE TIMES. HES STILL AT LEWIS AND CLARK.\n\nVIOLENCE DIDNT END AND IT STILL HASNT ENDED\n\nITS REALLY ONLY INCLUSIVE TO ABLE-BODIED CIS-HET WHITE PEOPLE WHO GREW UP WITH MONEY\n\nVERY GOOD AT OTHERING THOSE WHO DONT FIT INTO THAT BOX\n\nBLATANT RACISM AND DISCRIMINATION\n\nWOKE WHITE KIDS\n\nLACK OF DIVERSITY\n\nWE NEED POC REPRESENTATIO N IN ALL DEPARTMENTS AND THE STUDENT BODY\n\nLC DOESNT CARE ABOUT MINORITY GROUPS\n\nNOT GOOD AT HELPING DISABLED STUDENTS\n\nDOES NOT TRULY GIVE THEIR STUDENTS WITH ALLERGIES SAFE EATING SPACES\n\nACCESSIBILITY\n\nABLEISM\n\nTHE FACT THAT DISABLED STUDENTS AND PEOPLE HAVE LITTLE TO NO ACCESS OR VOICE\n\nLEWIS AND CLARK IS INACCESSIBLE TO ITS CORE\n\nIT TOOK ME A YEAR AND A HALF TO GET ACCOMODATIONS\n\nLEWIS AND CLARK COLLEGE BARELY QUALIFIES UNDER ADA DESCRIPTIONS\n\nARE DISABLED PEOPLE JUST NOT WORTH IT?\n\nTHE CAMPUS IS VERY INACCESSIBLE\n\nCRIMINALIZATION TOWARD OTHER STUDENTS WITH DIFFERENT POLITICAL BELIEFS\n\nINTOLERANCE TO PEOPLE THAT THINK DIFFERENTLY THAN THEM\n\nCANCELING\n\nHYPERSENSITIVITY\n\nEXCLUSIVITY\n\nINCONSISTENT WITH THE HELP THEY OFFER\n\nTHE SERVICES THEY OFFER STUDENTS ARE OFTEN INSUFFICIENT\n\nSEEING RESOURCES STRIPPED AWAY DUE TO LACK OF MONEY\n\nTUITION FEES INCREASE\n\nHIGH TUITION COSTS MAKE THIS INSTITUTION DIFFICULT TO ENTER AS IT IS\n\nJOB AVAILABILITY IS VERY LOW\n\nTRYING TO PAY FOR COLLEGE WHICH IS EXTRAORDINARILY DIFFICULT AND A HUGE SOURCE OF STRESS\n\nFINANCIAL PROBLEMS\n\nTHEY NEED RICH STUDENTS MORE THAN THEY WANT POC HERE\n\nI AM SCRAPING THROUGH THIS DEGREE\n\nMONEY\n\nPEOPLE AT LC LACK THE BASIC LIFE SKILLS TO SUPPORT THEIR WELL BEING\n\nWE DONT HAVE A LOT OF SUPPORT IN THAT PROCESS\n\nISOLATION AND LONELINESS\n\nIT IS SO EASY TO FEEL ISOLATED AND ALONE AT THIS SCHOOL\n\nMY OWN MENTAL HEALTH\n\nNOT HAVING EASY ACCESS TO MENTAL HEALTH RESOURCE\n\nTEACHERS ARE NOT TRAUMA INFORMED ABOUT MENTAL HEALTH\n\nISOLATIONn\nLEWIS AND CLARK, LIKE ANY OTHER INSTITUTION, IS OPPRESSIVE AND ISNT DOING ANYTHING TO CHANGEn\nI CANT WAIT TO LEAVE AND NEVER COME BACK"; // our text to display
let x

let y // current position of the text
function setup() {
  createCanvas(2000, 2000);
  background(255);

  // // create the font
  // font = createFont("Times New Roman", 64, true); 
  textFont("Times New Roman")
  textSize(50)

  textStyle(ITALIC)
  // start the text off screen halfway down the canvas
  x = 10;
  y = 800;



}
function draw() {
	background (0, 0, 0)
fill(255)
	text(str, x, y, 800)

	y = y - 1

//   // draw a full screen partially opaque white rectangle for the blur
//   fill(255, 30);
//   rect(0, 0, width, height);


//   // set the fill for the text
//   fill(0, 70);

//   // If the head of the text has started to go off screen, 
//   // draw a second copy behind it by 50 pixels
//   if (x < 0) {

//     text(str, x + textWidth(str) + 50, y);
//   }

//   // if the first copy of the text is completely offscreen, set x to be 
//   // at the current location of the second copy
//   if (x <= -textWidth(str)) {
//     x = x + textWidth(str) + 50;
//   }

//   // Draw the text
//   text(str, x, y);
//   // move the position one to the left
//   x--;
}
